In [2]:
import numpy as np

x = np.array([1,2,3,4,5])

print("Data type : ", x.dtype)

Data type :  int32


In [3]:
import numpy as np

x = np.array([1,2,3,4,54646464646464646])

print("Data type : ", x.dtype)

Data type :  int64


In [4]:
import numpy as np

x = np.array([1.1, 2.5, 3.8, 4.44, 5466])

print("Data type : ", x.dtype)

Data type :  float64


In [5]:
import numpy as np

x = np.array([1.1, 2.5, 3.8, 4.44, 5.44454546464645681244444466])

print("Data type : ", x.dtype)

Data type :  float64


In [6]:
import numpy as np

x = np.array(["a","b","c"])

print("Data type : ", x.dtype)

Data type :  <U1


In [8]:
import numpy as np

x = np.array(["a","b","c",1,2,3])

print("Data type : ", x.dtype)

Data type :  <U11


In [9]:
import numpy as np

x = np.array([1,2,3,4,5])

print("Data type : ", x.dtype)

Data type :  int32


In [10]:
import numpy as np

x = np.array([1,2,3,4,5], dtype = np.int8)

print("Data type : ", x.dtype)

Data type :  int8


In [11]:
import numpy as np

x = np.array([1,2,3,4,5], dtype = "f")

print("Data type : ", x.dtype)
print(x)

Data type :  float32
[1. 2. 3. 4. 5.]


In [15]:
import numpy as np

x = np.array([1,2,3,4,5])

new  = np.float32(x)

new_again = np.int_(x)

print(x)
print("Data type : ", x.dtype)
print(new)
print("Data type : ", new.dtype)
print(new_again)
print("Data type : ", new_again.dtype)

[1 2 3 4 5]
Data type :  int32
[1. 2. 3. 4. 5.]
Data type :  float32
[1 2 3 4 5]
Data type :  int32


In [19]:
import numpy as np

x = np.array([1,2,3,4,5])

x_new = x.astype("f")

print(x)
print(x_new)

[1 2 3 4 5]
[1. 2. 3. 4. 5.]


# shape

In [3]:
import numpy as np

x= np.array([[1,2,3,4],[5,6,7]])
print(x)
print() # For 1 line gap
print(x.shape)

[list([1, 2, 3, 4]) list([5, 6, 7])]

(2,)


C:\Users\pc\AppData\Local\Temp/ipykernel_1548/1119235366.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  x= np.array([[1,2,3,4],[5,6,7]])


In [24]:
import numpy as np

x= np.array([1,2,3,4],ndmin = 4)
print(x)
print() # For 1 line gap
print(x.ndim)
print() # For 1 line gap
print(x.shape)

[[[[1 2 3 4]]]]

4

(1, 1, 1, 4)


In [1]:
import numpy as np

x= np.array([1,2,3,4,5,6])

print(x)
print(x.ndim, "Dimension array")
print() # For 1 line gap

y = x.reshape(3,2)
print(y)
print(y.ndim,"Dimension array")

[1 2 3 4 5 6]
1 Dimension array

[[1 2]
 [3 4]
 [5 6]]
2 Dimension array


In [5]:
import numpy as np

x= np.array([1,2,3,4,5,6])

y = x.reshape(3,3)
print(y)
print(y.ndim,"Dimension array")

ValueError: cannot reshape array of size 6 into shape (3,3)

In [11]:
import numpy as np

x= np.array([1,2,3,4,5,6,7,8,9])

y = x.reshape(3,3)
print(y)
print() # For 1 line gap
print(y.ndim,"Dimension array")

[[1 2 3]
 [4 5 6]
 [7 8 9]]

2 Dimension array


In [17]:
import numpy as np

x= np.array([1,2,3,4,5,6,7,8,9,10,11,12])

y = x.reshape(1,6,2)
print(y)
print() # For 1 line gap
print(y.ndim,"Dimension array")

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]
  [11 12]]]

3 Dimension array


In [19]:
import numpy as np

x= np.array([1,2,3,4,5,6,7,8,9,10,11,12])

y = x.reshape(3,2,2)
print(y)
print() # For 1 line gap
print(y.ndim,"Dimension array")

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]

3 Dimension array


In [22]:
import numpy as np

x= np.array([1,2,3,4,5,6,7,8,9,10,11,12])

print(x)
print(x.ndim, "Dimension array")
print() # For 1 line gap

y = x.reshape(2,3,2)
print(y)
print(y.ndim,"Dimension array")
print() # For 1 line gap

z = x.reshape(-1)
print(z)
print(z.ndim,"Dimension array")

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1 Dimension array

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3 Dimension array

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1 Dimension array
