In [1]:
!pip install numpy

In [9]:
x = [1,2,"Hello","@"]
print(x)

[1, 2, 'Hello', '@']


In [10]:
type(x)

list

In [11]:
print(type(x))

<class 'list'>


In [13]:
import numpy as np

x = np.array([1,2,"Hello","@"])
print (x)

['1' '2' 'Hello' '@']


In [14]:
type(x)

numpy.ndarray

# %timeit [j**4 for j in range (1,9)]

In [19]:
import numpy as np

%timeit [np.arange(1,9)**4]

5.38 µs ± 189 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# Converting list to array through numpy

In [20]:
import numpy as np

x = [1,2,3,4]

y = np.array(x)
y

array([1, 2, 3, 4])

In [21]:
print (y)

[1 2 3 4]


In [22]:
print (type(y))

<class 'numpy.ndarray'>


In [5]:
import numpy as np

l = []

for i in range (1,5):
    inputing  = int(input('Enter the number: '))
    l.append(inputing)

print (np.array(l))

Enter the number: 12
Enter the number: 45
Enter the number: 78
Enter the number: 49
[12 45 78 49]


In [17]:
two_dim_array = np.array([[1,2,3,4],[5,6,7,8]])
print(two_dim_array)

[[1 2 3 4]
 [5 6 7 8]]


In [15]:
print(two_dim_array.ndim)

2


In [18]:
two_dim_array = np.array([[1,2,3,4],[5,6,7]])
print(two_dim_array)

[list([1, 2, 3, 4]) list([5, 6, 7])]


C:\Users\pc\AppData\Local\Temp/ipykernel_16256/3232273983.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  two_dim_array = np.array([[1,2,3,4],[5,6,7]])


In [22]:
three_dim_array = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(three_dim_array)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [23]:
print(three_dim_array.ndim)

3


In [26]:
n_dim_array = np.array([1,2,3,4], ndmin = 10)
print(n_dim_array)

[[[[[[[[[[1 2 3 4]]]]]]]]]]


In [27]:
print(n_dim_array.ndim)

10


In [32]:
import numpy as np

array_1_dim_zeros = np.zeros(5)
print (array_1_dim_zeros)

[0. 0. 0. 0. 0.]


In [31]:
type(array_1_dim_zeros.ndim)

int

In [44]:
array_2_dim_zeros = np.zeros((3,5))
print (array_2_dim_zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [41]:
array_3_dim_zeros = np.zeros(((3,5,2)))
print (array_3_dim_zeros)

[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


In [42]:
import numpy as np

array_1_dim_ones = np.ones(5)
print (array_1_dim_ones)

[1. 1. 1. 1. 1.]


In [45]:
import numpy as np

array_empty = np.empty(5)
print (array_empty)

[1. 1. 1. 1. 1.]


In [46]:
array_arange = np.arange(5)
print(array_arange)

[0 1 2 3 4]


In [47]:
array_diagonal = np.eye(3)
print(array_diagonal)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [48]:
array_diagonal = np.eye(3,5)
print(array_diagonal)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [49]:
array_linspace = np.linspace(0,10, num=5)
print(array_linspace)

[ 0.   2.5  5.   7.5 10. ]


In [52]:
array_linspace = np.linspace(0,20)
print(array_linspace)

[ 0.          0.40816327  0.81632653  1.2244898   1.63265306  2.04081633
  2.44897959  2.85714286  3.26530612  3.67346939  4.08163265  4.48979592
  4.89795918  5.30612245  5.71428571  6.12244898  6.53061224  6.93877551
  7.34693878  7.75510204  8.16326531  8.57142857  8.97959184  9.3877551
  9.79591837 10.20408163 10.6122449  11.02040816 11.42857143 11.83673469
 12.24489796 12.65306122 13.06122449 13.46938776 13.87755102 14.28571429
 14.69387755 15.10204082 15.51020408 15.91836735 16.32653061 16.73469388
 17.14285714 17.55102041 17.95918367 18.36734694 18.7755102  19.18367347
 19.59183673 20.        ]


In [55]:
array_linspace = np.linspace(0,20,9)
print(array_linspace)

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20. ]


# Random


In [59]:
import numpy as np

x= np.random.rand(5)

print(x)

[0.64693843 0.07488087 0.52206255 0.78266139 0.78497859]


In [ ]:
import numpy as np

x= np.random.rand(5)

print(x)

In [61]:
import numpy as np

y= np.random.rand(2,5)

print(y)

[[0.69918691 0.02935616 0.42253382 0.42854587 0.97300615]
 [0.52008986 0.74675224 0.10065713 0.66372846 0.56064802]]


# randn

In [62]:
import numpy as np

x= np.random.randn(5)

print(x)

[-0.63393785  0.07015947 -0.74997583 -0.01281238 -0.27976401]


In [63]:
import numpy as np

y= np.random.randn(2,5)

print(y)

[[-1.00936395 -0.76862902 -1.60749083  0.80537434 -0.42308385]
 [-0.80266258  0.74817387  0.8071598   0.47556164 -0.79924753]]


# ranf()

In [65]:
import numpy as np

x= np.random.ranf(5)

print(x)

[0.90994073 0.36215823 0.21479807 0.98025849 0.02864129]


In [66]:
import numpy as np

y= np.random.ranf(2,5)

print(y)

TypeError: random_sample() takes at most 1 positional argument (2 given)

# randint()


In [69]:
# x = np.ramdom.randint(min_value, max_value, total_value)
x = np.random.randint(10,24,5)
print(x)

[20 11 19 11 15]


In [70]:
x = np.random.randint(10,24,5)
print(x)

[22 16 12 13 20]
