# Arithmetic operation

# Addition 

In [4]:
import numpy as np

var = np.array([1,2,3,4])

var_add = var + 5

print (var_add)

[6 7 8 9]


In [1]:
import numpy as np

var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

var_add = var1 + var2

print (var_add)

[2 4 6 8]


# Using function

In [20]:
import numpy as np

var = np.array([1,2,3,4])

var_add = np.add(var,5)

print (var_add)

[6 7 8 9]


In [21]:
import numpy as np

var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

var_add = np.add(var1,var2)

print (var_add)

[2 4 6 8]


# Subtraction 

In [3]:
import numpy as np

var = np.array([1,2,3,4])

var_sub = var - 5

print (var_sub)

[-4 -3 -2 -1]


In [5]:
import numpy as np

var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

var_sub = var1 - var2

print (var_sub)

[0 0 0 0]


# Using function

In [22]:
import numpy as np

var = np.array([1,2,3,4])

var_sub = np.subtract(var,5) 

print (var_sub)

[-4 -3 -2 -1]


In [23]:
import numpy as np

var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

var_sub = np.subtract(var1,var2) 

print (var_sub)

[0 0 0 0]


# Multiplication 

In [6]:
import numpy as np

var = np.array([1,2,3,4])

var_mul = var * 5

print (var_mul)

[ 5 10 15 20]


In [7]:
import numpy as np

var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

var_mul = var1 * var2

print (var_mul)

[ 1  4  9 16]


# Using function

In [24]:
import numpy as np

var = np.array([1,2,3,4])

var_mul = np.multiply(var,5)

print (var_mul)

[ 5 10 15 20]


In [25]:
import numpy as np

var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

var_mul = np.multiply(var1,var2)

print (var_mul)

[ 1  4  9 16]


# Division 

In [8]:
import numpy as np

var = np.array([1,2,3,4])

var_div = var / 5

print (var_div)

[0.2 0.4 0.6 0.8]


In [14]:
import numpy as np

var1 = np.array([10,24,37,44])
var2 = np.array([1,2,3,4])

var_div = (var1 / var2)

print (var_div)

[10.         12.         12.33333333 11.        ]


# Using function

In [26]:
import numpy as np

var = np.array([1,2,3,4])

var_div = np.divide(var,5) 

print (var_div)

[0.2 0.4 0.6 0.8]


In [27]:
import numpy as np

var1 = np.array([10,24,37,44])
var2 = np.array([1,2,3,4])

var_div = np.divide(var1,var2)

print (var_div)

[10.         12.         12.33333333 11.        ]


# Modulus

In [19]:
import numpy as np

var = np.array([17,2,3,4])

var_mod = var % 3

print (var_mod)

[2 2 0 1]


In [17]:
import numpy as np

var = [1, 2., 3, 5]

var_rec = np.reciprocal(var)

print (var_rec)

[1.         0.5        0.33333333 0.2       ]


In [22]:
import numpy as np

var = [1, 2, 3, 5]

var_rec = np.reciprocal(var)

print (var_rec)

[1 0 0 0]


In [25]:
import numpy as np

var1 = np.array([[10,24,37,44],[4,5,6,7]])
var2 = np.array([[1,2,3,4],[7,8,5,9]])

print(var1)
print()
print(var2)
print()

var_add = np.add(var1,var2)

print (var_add)

[[10 24 37 44]
 [ 4  5  6  7]]

[[1 2 3 4]
 [7 8 5 9]]

[[11 26 40 48]
 [11 13 11 16]]


In [26]:
import numpy as np

var1 = np.array([[10,24,37,44],[4,5,6,7]])
var2 = np.array([[1,2,3,4],[7,8,5,9]])

print(var1)
print()
print(var2)
print()

var_mul = np.multiply(var1,var2)

print (var_mul)

[[10 24 37 44]
 [ 4  5  6  7]]

[[1 2 3 4]
 [7 8 5 9]]

[[ 10  48 111 176]
 [ 28  40  30  63]]


# Arithmetic functions

In [31]:
import numpy as np

var = np.array([5,2,3,4])

print ("Min number is : ", np.min(var))
print ("Max number is : ", np.max(var))

Min number is :  2
Max number is :  5


In [10]:
import numpy as np

var = np.array([5,2,3,1])

print ("Min number is : ", np.min(var),"and the INDEX of the min number is : ", np.argmin(var))
print ("Max number is : ", np.max(var),"and the INDEX of the min number is : ", np.argmax(var))

Min number is :  1 and the INDEX of the min number is :  3
Max number is :  5 and the INDEX of the min number is :  0


In [33]:
import numpy as np

var = np.array([[5,21,31,1],[11,21,14,51]])
print (var)

# axis 0 means column wise              and         axis 1 row wise

print (np.min(var,axis = 0),"         Min number (axis 0 means column wise)")
print (np.min(var,axis = 1),"               Max number (axis 1 means row wise)")

[[ 5 21 31  1]
 [11 21 14 51]]
[ 5 21 14  1]          Min number (axis 0 means column wise)
[ 1 11]                Max number (axis 1 means row wise)


In [37]:
import numpy as np

var = np.array([16,4,9,3])

print (np.sqrt(var))

[4.         2.         3.         1.73205081]


In [39]:
import numpy as np

var = np.array([1, 45,90])

print (np.sin(var))

[0.84147098 0.85090352 0.89399666]


In [41]:
import numpy as np

var = np.array([1,45,90])

print (np.cos(var))

[ 0.54030231  0.52532199 -0.44807362]


In [44]:
import numpy as np

var = np.array([1,2,3,4])

print ("Cumulative sum : ", np.cumsum(var))

Cumulative sum :  [ 1  3  6 10]


In [3]:
import numpy as np
a = np.array([[2, 4], [3, 5]]) 
print (a)
print ()
b=np.mean(a,axis=0)  
c=np.mean(a,axis=1)  
print(b)  
print(c)    

[[2 4]
 [3 5]]

[2.5 4.5]
[3. 4.]
